-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT mill.ID AS ENTITY_ID, mill.NAME AS ENTITY_NAME,
       mill.REGION, mill.CATEGORY, mill.RISK_TIER, mill.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.DISPATCH_COUNT) AS DISPATCH_COUNT,
       SUM(observation.TRACED_TONNES) AS TRACED_TONNES,
       SUM(observation.CPO_TONNES) AS CPO_TONNES,
       SUM(observation.FLAG_COUNT) AS FLAG_COUNT,
       SUM(observation.CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       SUM(observation.LOTS_HELD) AS HELD_COUNT,
       SUM(observation.RECONCILIATION_DUE) AS RECONCILIATION_DUE,
       SUM(observation.RECONCILIATION_RECEIVED) AS RECONCILIATION_RECEIVED,
       100.0 * SUM(observation.TRACED_TONNES) / NULLIF(SUM(observation.CPO_TONNES), 0) AS TRACEABILITY_PCT,
       100.0 * SUM(observation.CONFIRMED_COUNT) / NULLIF(SUM(observation.FLAG_COUNT), 0) AS FLAG_PRECISION_PCT,
       100.0 * SUM(observation.RECONCILIATION_RECEIVED) / NULLIF(SUM(observation.RECONCILIATION_DUE), 0) AS RECONCILIATION_PCT,
       AVG(observation.MB_VARIANCE_PCT) AS AVG_MB_VARIANCE_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.MILL_DAILY observation
JOIN RAW.MILLS mill ON mill.ID = observation.ENTITY_ID
GROUP BY mill.ID, mill.NAME, mill.REGION, mill.CATEGORY, mill.RISK_TIER, mill.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(DISPATCH_COUNT) AS DISPATCH_COUNT, SUM(TRACED_TONNES) AS TRACED_TONNES,
       SUM(CPO_TONNES) AS CPO_TONNES,
       SUM(FLAG_COUNT) AS FLAG_COUNT, SUM(CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       100.0 * SUM(TRACED_TONNES) / NULLIF(SUM(CPO_TONNES), 0) AS TRACEABILITY_PCT
FROM RAW.MILL_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.SIGNAL_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT RISK_SIGNAL, SUM(FLAG_COUNT) AS FLAG_COUNT,
       SUM(CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       SUM(LOTS_HELD) AS HELD_COUNT,
       SUM(TRACED_TONNES) AS FLAGGED_DAY_TRACED_TONNES,
       100.0 * SUM(CONFIRMED_COUNT) / NULLIF(SUM(FLAG_COUNT), 0) AS FLAG_PRECISION_PCT
FROM RAW.MILL_DAILY
WHERE FLAG_COUNT > 0
GROUP BY RISK_SIGNAL;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(DISPATCH_COUNT) AS DISPATCHES, SUM(TRACED_TONNES) AS TRACED,
         SUM(CPO_TONNES) AS DISPATCHED,
         SUM(FLAG_COUNT) AS FLAGS, SUM(CONFIRMED_COUNT) AS CONFIRMED,
         SUM(LOTS_HELD) AS HELD,
         SUM(RECONCILIATION_DUE) AS RECONCILIATION_DUE, SUM(RECONCILIATION_RECEIVED) AS RECONCILIATION_RECEIVED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.MILL_DAILY
), portfolio AS (SELECT COUNT(*) AS MILL_COUNT FROM RAW.MILLS),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING, SUM(REQUIRED_QTY) AS REGISTERED
  FROM RAW.SUPPLIER_REGISTRY
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Traceability to Plantation' AS TITLE,
         100.0 * TRACED / NULLIF(DISPATCHED, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'CPO Custody Transfers', DISPATCHES, '' FROM observations
  UNION ALL SELECT 3, 'CPO Dispatched (kt)', DISPATCHED / 1e3, '' FROM observations
  UNION ALL SELECT 4, 'Custody Flags', FLAGS, '' FROM observations
  UNION ALL SELECT 5, 'Confirmed Custody Breaks', CONFIRMED, '' FROM observations
  UNION ALL SELECT 6, 'Flag Precision', 100.0 * CONFIRMED / NULLIF(FLAGS, 0), '%' FROM observations
  UNION ALL SELECT 7, 'Lots Held at Refinery', HELD, '' FROM observations
  UNION ALL SELECT 8, 'Mass-Balance Reconciliation Rate', 100.0 * RECONCILIATION_RECEIVED / NULLIF(RECONCILIATION_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Mills Monitored', MILL_COUNT, '' FROM portfolio
  UNION ALL SELECT 10, 'Supplier Link Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Supplier Verifications Pending', PENDING, '' FROM documents
  UNION ALL SELECT 12, 'Registered FFB Suppliers', REGISTERED, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.SIGNAL_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
