-- Custody-break risk scoring and CPO dispatch forecast over the synthetic snapshot.
-- Predicts P(confirmed custody break in the next 7 days) per mill and
-- reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.CUSTODY_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, m.CATEGORY, m.RISK_TIER, m.PROGRAM_YEARS,
       r.MB_VARIANCE_PCT, r.UNTRACED_PCT,
       AVG(r.MB_VARIANCE_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS MB_VARIANCE_7D,
       SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS CONFIRMED_30D,
       -- Days since the last mass-balance reconciliation was due, and the 30-day return rate.
       DATEDIFF('day', MAX(IFF(r.RECONCILIATION_DUE = 1, r.EVENT_DATE, NULL)) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), r.EVENT_DATE) AS DAYS_SINCE_RECON,
       COALESCE(SUM(r.RECONCILIATION_RECEIVED) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW)
         / NULLIF(SUM(r.RECONCILIATION_DUE) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW), 0), 1) AS RECON_RATE_30D,
       IFF(SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'BREAK', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.MILL_DAILY r JOIN RAW.MILLS m ON m.ID = r.ENTITY_ID
-- Weighbridge system outages are area-wide, not mill-driven, so they are excluded from training.
WHERE r.RISK_SIGNAL <> 'Weighbridge system outage';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.CUSTODY_TRAIN AS
SELECT CATEGORY, RISK_TIER, PROGRAM_YEARS, MB_VARIANCE_PCT, UNTRACED_PCT, MB_VARIANCE_7D, CONFIRMED_30D, DAYS_SINCE_RECON, RECON_RATE_30D, LABEL
FROM ML.CUSTODY_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.CUSTODY_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, RISK_TIER, PROGRAM_YEARS, MB_VARIANCE_PCT, UNTRACED_PCT, MB_VARIANCE_7D, CONFIRMED_30D, DAYS_SINCE_RECON, RECON_RATE_30D, LABEL
FROM ML.CUSTODY_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.CUSTODY_RISK_MODEL(
  INPUT_DATA => TABLE(ML.CUSTODY_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.CUSTODY_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.CUSTODY_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'PROGRAM_YEARS', PROGRAM_YEARS,
           'MB_VARIANCE_PCT', MB_VARIANCE_PCT, 'UNTRACED_PCT', UNTRACED_PCT,
           'MB_VARIANCE_7D', MB_VARIANCE_7D, 'CONFIRMED_30D', CONFIRMED_30D,
           'DAYS_SINCE_RECON', DAYS_SINCE_RECON, 'RECON_RATE_30D', RECON_RATE_30D)):probability:BREAK::FLOAT AS P
  FROM ML.CUSTODY_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'BREAK', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'BREAK', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'BREAK', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'BREAK', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per mill (label unknown, so excluded from features).
CREATE TABLE ML.CUSTODY_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.CUSTODY_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.CUSTODY_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'PROGRAM_YEARS', PROGRAM_YEARS,
           'MB_VARIANCE_PCT', MB_VARIANCE_PCT, 'UNTRACED_PCT', UNTRACED_PCT,
           'MB_VARIANCE_7D', MB_VARIANCE_7D, 'CONFIRMED_30D', CONFIRMED_30D,
           'DAYS_SINCE_RECON', DAYS_SINCE_RECON, 'RECON_RATE_30D', RECON_RATE_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:BREAK::FLOAT, 4) AS BREAK_PROB_7D,
       CASE WHEN P:probability:BREAK::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:BREAK::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Network-wide daily CPO dispatch forecast (14 days), for refinery intake planning.
CREATE VIEW ML.DAILY_DISPATCHES AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(DISPATCH_COUNT)::FLOAT AS DISPATCH_COUNT
FROM RAW.MILL_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.DISPATCH_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_DISPATCHES),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'DISPATCH_COUNT'
);

CREATE TABLE ML.DISPATCH_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS DISPATCH_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.DISPATCH_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
